### ISSUE TITLE
file question

### ISSUE THREAD

**Issue by CodingPerson** [Anna146/snorkel_labeling#1]
Could you please provide the file in the code？
df_golden = pd.read_csv("/home/tigunova/PycharmProjects/snorkel_labels/data/hobby/gold_dev.csv")
df_golden = pd.read_csv("/home/tigunova/PycharmProjects/snorkel_labels/data/hobby/gold_validation.csv")

**Comment by Anna146** [comment]
Done! Sorry I did not add them earlier

**Comment by CodingPerson** [comment]
Could you please provide another missing documents?thank you
reader = csv.reader(open("/home/tigunova/PycharmProjects/snorkel_labels/data/hobby/labeling_lf/%d.csv" % (worker_index)))




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anna146/snorkel_labeling"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 晚上10:47
收件人:&nbsp;"Anna146/snorkel_labeling"<snorkel_labeling@noreply.github.com&gt;;
抄送:&nbsp;"1440624049"<1440624049@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Anna146/snorkel_labeling] file question (#1)





 
Done! Sorry I did not add them earlier
